### ISSUE TITLE
SourceMap referes to wrong files and lines

### ISSUE THREAD

**Issue by dawidk92** [gruntjs/grunt-contrib-cssmin#216] opened 2015-05-13 15:07 UTC
Im generating SourceMap by grunt-sass (1.0.0) and Im including foundation (5.5.2) into it

```
sass: {
    options: {
        includePaths: [
            'bower_components/foundation/scss'
        ],
        sourceMap: true
    },
    dist: {
        files: { '<%= dir.css %>/main.css': '<%= dir.sass %>/app.scss' }
    }
}
```

It works fine but when Im using cssmin (0.12.3) SourceMap breaks and doesnt work properly anymore

```
cssmin: {
    combine: {
        options: {
            keepSpecialComments: 0,
            sourceMap: true
        },
        files: {
            '<%= dir.css %>/main.css': ['<%= dir.css %>/main.css']
        }
    }
}
```

**Comment by XhmikosR** [comment] 2017-03-26 09:04
Duplicate of #204 #248

**Closed by XhmikosR** 2017-03-26 09:04 UTC
