### ISSUE TITLE
why removed banner option?

### ISSUE THREAD

**Issue by joebnb** [gruntjs/grunt-contrib-cssmin#226] opened 2015-06-03 11:06 UTC
really i dont know why...

**Comment by sindresorhus** [comment] 2015-06-03 15:19
Duplicate of https://github.com/gruntjs/grunt-contrib-cssmin/issues/176 and https://github.com/gruntjs/grunt-contrib-cssmin/issues/184

**Closed by sindresorhus** 2015-06-03 15:19 UTC
